#!/usr/bin/env python3
"""Build script for notebooks/demo.ipynb.

This is the v3 notebook — a clean, focused rebuild of the conveyor-perception
demo for the EverestLabs AI Engineer interview. Demo v1 and v2 are kept in
the repo as knowledge sources / reference; v3 is the active, fresh build.

v3 design goals (locked Aug 22 2026, with Ronie Joseph):
  - 12-15 cells max (no half-numbers, no §-prefix nonsense)
  - Each cell has one job; cells do what they say
  - v2's colab_session.py is the SessionState singleton (re-used as-is)
  - Cells are tested one-at-a-time: paste → run → screenshot → next

Cell narrative (planned):
  0.  Title             (markdown, 1-screen pitch)
  1.  Runtime + env     (GPU, disk, RAM, Python)
  2.  Install + clone   (minimal open-source deps)
  3.  State + toggles   (SessionState + module toggle UI)
  4.  Load abstractions (4 framework abstractions)
  5.  Load modules      (7+1 JD modules)
  6.  Data registry     (what's on disk?)
  7.  Data download     (idempotent)
  8.  Train             (cached on re-run)
  9.  Compare           (side-by-side metrics)
  10. Pipeline          (Detector→Tracker→Drift→Triage→Maintenance)
  11. Visual Analytics  (the impressive part)
  12. Production path   (Roboflow Inference, library mode)
  13. Triage + monitor  (queue + robustness + dashboard)
  14. Coach + summary   (Gemini review + downloadable session log)
  15. Comparison        (T4 vs EverestLabs target)
"""
from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Cell builder helpers (same pattern as v2 — keep it simple)
# ---------------------------------------------------------------------------

def code(*lines: str) -> dict[str, Any]:
    """Build a code cell from individual source lines (1 string per line)."""
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [l + "\n" for l in lines],
    }


def md(*lines: str) -> dict[str, Any]:
    """Build a markdown cell from individual source lines."""
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [l + "\n" for l in lines],
    }


CELLS: list[dict[str, Any]] = []


# ---------------------------------------------------------------------------
# Cell 0 (markdown): Title — 1-screen pitch
# ---------------------------------------------------------------------------
CELLS.append(md(
    "# Conveyor perception",
    "",
    "**An end-to-end industrial CV pipeline on a free T4:** real recycling data → trained model → live detection → drift monitoring → triage decisions.",
    "",
    "- **Runtime:** Google Colab T4 (free tier, ~12h cap).  ",
    "- **Data:** bundled 4-class recycling set (CC BY 4.0).  ",
    "- **Model:** YOLO26s, trained in-kernel, cached on re-run.  ",
    "- **Goal:** show the loop — train → infer → drift → triage → maintain — on real data, in <5 minutes.",
))


# ---------------------------------------------------------------------------
# Cell 1 (code): Runtime + env check
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 1: Runtime + env check ---",
    "import os, sys, json, platform",
    "from pathlib import Path",
    "",
    "# --- 1. Colab or local? ---",
    "IN_COLAB = 'google.colab' in sys.modules",
    "print(f'  Runtime: {\"Google Colab\" if IN_COLAB else \"Local (\" + platform.node() + \")\"}')",
    "",
    "# --- 2. Python + key libs (skip import if missing) ---",
    "print(f'  Python: {sys.version.split()[0]}  ({sys.executable.split(\"/\")[-1]})')",
    "for mod in ['numpy', 'torch', 'ultralytics', 'supervision', 'roboflow']:",
    "    try:",
    "        m = __import__(mod)",
    "        v = getattr(m, '__version__', '?')",
    "        print(f'  {mod:14s} {v}')",
    "    except ImportError:",
    "        print(f'  {mod:14s} — not installed yet (cell 2 will install)')",
    "",
    "# --- 3. GPU (or warn if CPU-only) ---",
    "_gpu = 'unknown'",
    "try:",
    "    import torch",
    "    _gpu = torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU only'",
    "except Exception:",
    "    pass",
    "print(f'  GPU:    {_gpu}')",
    "",
    "# --- 4. Disk + RAM ---",
    "_disk_free = '?'",
    "try:",
    "    import shutil",
    "    _u = shutil.disk_usage('/')",
    "    _disk_free = f'{_u.free / 1e9:.1f} GB free of {_u.total / 1e9:.1f} GB'",
    "except Exception:",
    "    pass",
    "print(f'  Disk:   {_disk_free}')",
    "",
    "# --- 5. Locate the repo (for local runs) — Colab gets cloned by cell 2 ---",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "if not IN_COLAB:",
    "    # Walk up until we find the repo root (contains pyproject.toml)",
    "    while not (REPO / 'pyproject.toml').exists() and REPO != REPO.parent:",
    "        REPO = REPO.parent",
    "print(f'  Repo:   {REPO}{\" (will be cloned here by cell 2)\" if IN_COLAB else \"\"}')",
    "",
    "# NOTE: colab_session + the state singleton are intentionally NOT used here.",
    "# Cell 1 runs BEFORE the clone (cell 2), so the repo isn't on disk yet — any",
    "# `import colab_session` would crash with ModuleNotFoundError. State init is",
    "# deferred to cell 3, which runs after the clone + install are done. (Aug 22 2026)",
    "print()",
    "print('  ✓ env check done.  Next: cell 2 (clone + install).')",
))


# ---------------------------------------------------------------------------
# Cell 2 (code): Install + clone — minimal open-source deps, idempotent clone
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 2: Install + clone ---",
    "import os, sys, subprocess, importlib",
    "from pathlib import Path",
    "",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "",
    "# --- 1. Clone repo (idempotent — skip if pyproject.toml already there) ---",
    "if IN_COLAB:",
    "    if (REPO / 'pyproject.toml').exists():",
    "        print(f'  Repo already at {REPO} (skipping clone)')",
    "    else:",
    "        print(f'  Cloning conveyor-perception -> {REPO}...')",
    "        REPO.parent.mkdir(parents=True, exist_ok=True)",
    "        subprocess.run(",
    "            ['git', 'clone', '--depth=1',",
    "             'https://github.com/roniejosephv-star/conveyor-perception.git',",
    "             str(REPO)],",
    "            check=True,",
    "        )",
    "        print('  ✓ cloned.')",
    "else:",
    "    print(f'  Local repo at {REPO} (skipping clone)')",
    "",
    "# --- 2. Add REPO + REPO/notebooks to sys.path (colab_session.py lives in notebooks/) ---",
    "for _p in (REPO, REPO / 'notebooks'):",
    "    _sp = str(_p)",
    "    if _sp not in sys.path:",
    "        sys.path.insert(0, _sp)",
    "print(f'  Path:  {REPO}  +  {REPO}/notebooks')",
    "",
    "# --- 3. Install minimal open-source deps (numpy/torch already on Colab) ---",
    "# 'trackers>=2.6.0' is for the ByteTrack tracker in TrackingPipeline. Without",
    "# it, the pipeline falls back to a simple IoU tracker (less robust to occlusion).",
    "INSTALL = ['ultralytics', 'supervision', 'opencv-python-headless', 'roboflow', 'trackers>=2.6.0']",
    "print(f'  Installing: {\", \".join(INSTALL)}')",
    "subprocess.check_call(",
    "    [sys.executable, '-m', 'pip', 'install', '-q', '--no-input', *INSTALL]",
    ")",
    "print('  ✓ installed.')",
    "",
    "# --- 4. Verify the key imports work (smoke test) ---",
    "print('  Verifying:')",
    "for _mod in ['ultralytics', 'supervision', 'roboflow']:",
    "    try:",
    "        _m = importlib.import_module(_mod)",
    "        _v = getattr(_m, '__version__', '?')",
    "        print(f'    {_mod:14s} {_v}  ok')",
    "    except ImportError as _e:",
    "        print(f'    {_mod:14s} FAIL  {_e}')",
    "",
    "# --- 5. Verify colab_session is now importable (the import cell 3 needs) ---",
    "try:",
    "    from colab_session import get_state",
    "    print('    colab_session  ok  (get_state() ready for cell 3)')",
    "except ImportError as _e:",
    "    print(f'    colab_session  FAIL  {_e}')",
    "",
    "# --- 6. Quick sanity check: list the repo top-level ---",
    "print(f'  Repo top-level:')",
    "for _entry in sorted(REPO.iterdir()):",
    "    if not _entry.name.startswith('.'):",
    "        print(f'    {_entry.name}')",
    "",
    "print()",
    "print('  ✓ install + clone done.  Next: cell 3 (state + toggles).')",
))


# ---------------------------------------------------------------------------
# Cell 3 (code): State + toggles — SessionState singleton + ipywidgets toggle UI
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 3: State + toggles ---",
    "import os, sys, subprocess",
    "from pathlib import Path",
    "",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "",
    "# --- 1. Defensive install: ipywidgets is needed for the toggle UI ---",
    "# (Colab has it pre-installed, but cell 3 should not assume cell 2 installed it.)",
    "try:",
    "    import ipywidgets  # noqa: F401",
    "    print('  ipywidgets: ok')",
    "except ImportError:",
    "    print('  Installing ipywidgets (toggle UI dep)...')",
    "    subprocess.check_call(",
    "        [sys.executable, '-m', 'pip', 'install', '-q', '--no-input', 'ipywidgets']",
    "    )",
    "    print('  ✓ installed.')",
    "",
    "# --- 2. Idempotent sys.path setup (cell 2 already did this; redo is harmless) ---",
    "for _p in (REPO, REPO / 'notebooks'):",
    "    _sp = str(_p)",
    "    if _sp not in sys.path:",
    "        sys.path.insert(0, _sp)",
    "",
    "# --- 3. Create the SessionState singleton (lives in builtins so every cell sees it) ---",
    "from colab_session import get_state, toggle_ui",
    "",
    "state = get_state()",
    "state.log('cell-3', action='init', note='state singleton + toggle UI ready')",
    "",
    "# --- 4. Show the toggle UI (4 framework abstractions + 8 JD modules) ---",
    "# Untick anything you want the pipeline to skip. Defaults: all enabled.",
    "print()",
    "print('  Toggle the components below — defaults are all enabled.')",
    "print('  Untick anything you want to skip in the pipeline.')",
    "print()",
    "ui = toggle_ui()",
    "display(ui)",
    "",
    "# --- 5. Print a summary of what's currently enabled (grouped) ---",
    "print()",
    "print('  Current toggles:')",
    "abstr_keys = [k for k in state.toggles if k.startswith('abstraction:')]",
    "mod_keys = [k for k in state.toggles if k.startswith('module:')]",
    "print('    4 framework abstractions:')",
    "for _k in abstr_keys:",
    "    _v = state.toggles[_k]",
    "    _icon = '✓' if _v else '○'",
    "    print(f'      {_icon} {_k}')",
    "print('    8 JD modules:')",
    "for _k in mod_keys:",
    "    _v = state.toggles[_k]",
    "    _icon = '✓' if _v else '○'",
    "    print(f'      {_icon} {_k}')",
    "",
    "_n_on = sum(state.toggles.values())",
    "_n_total = len(state.toggles)",
    "print()",
    "print(f'  ✓ state + toggles ready.  {_n_on}/{_n_total} components enabled.')",
    "print('  Next: cell 4 (load abstractions).')",
))


# ---------------------------------------------------------------------------
# Cell 4 (code): Load abstractions — the 4 framework abstractions
# (Detector, TrackingPipeline, DriftMonitor, MCPTriageSurface)
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 4: Load abstractions ---",
    "import os, sys",
    "from pathlib import Path",
    "",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "SRC = REPO / 'src'",
    "",
    "# --- 1. Path setup: src/ (for `import conveyor_perception`) + REPO/notebooks ---",
    "for _p in (REPO, REPO / 'notebooks', SRC):",
    "    _sp = str(_p)",
    "    if _sp not in sys.path:",
    "        sys.path.insert(0, _sp)",
    "",
    "# --- 2. Import the 4 abstraction classes (unconditional — fail fast on missing module) ---",
    "from colab_session import get_state",
    "from conveyor_perception.core.detection_pipeline import DetectionPipeline as Detector",
    "from conveyor_perception.core.tracking_pipeline import TrackingPipeline",
    "from conveyor_perception.core.drift_monitor import DriftMonitor",
    "from conveyor_perception.core.triage_surface import MCPTriageSurface, InMemoryAlertQueue",
    "",
    "state = get_state()",
    "loaded: dict = {}",
    "skipped: list = []",
    "",
    "# --- 3. Toggle-gated load (the toggle UI from cell 3 controls this) ---",
    "if state.toggles.get('abstraction:detector', True):",
    "    # Detector is just a class ref for now — model is wired in cell 8 after training.",
    "    loaded['detector'] = Detector",
    "    print('  ✓ Detector class loaded (YOLO26 + OpenCV DNN)')",
    "else:",
    "    skipped.append('abstraction:detector')",
    "    print('  ○ Detector skipped (toggle off)')",
    "",
    "if state.toggles.get('abstraction:tracker', True):",
    "    loaded['tracker'] = TrackingPipeline()",
    "    print('  ✓ TrackingPipeline instantiated (ByteTrack)')",
    "else:",
    "    skipped.append('abstraction:tracker')",
    "    print('  ○ TrackingPipeline skipped (toggle off)')",
    "",
    "if state.toggles.get('abstraction:drift_monitor', True):",
    "    loaded['drift_monitor'] = DriftMonitor(baseline_window=50, min_samples_for_drift=20)",
    "    print('  ✓ DriftMonitor instantiated (KS test + z-score + MAD)')",
    "else:",
    "    skipped.append('abstraction:drift_monitor')",
    "    print('  ○ DriftMonitor skipped (toggle off)')",
    "",
    "if state.toggles.get('abstraction:triage', True):",
    "    loaded['triage_surface'] = MCPTriageSurface('l1-triage', InMemoryAlertQueue())",
    "    print('  ✓ MCPTriageSurface instantiated (5 MCP tools)')",
    "else:",
    "    skipped.append('abstraction:triage')",
    "    print('  ○ MCPTriageSurface skipped (toggle off)')",
    "",
    "state.log('cell-4', action='load-abstractions', loaded=list(loaded.keys()), skipped=skipped)",
    "print()",
    "print(f'  ✓ loaded {len(loaded)}/4 abstractions, skipped {len(skipped)}.')",
    "print('  Next: cell 5 (load modules).')",
))


# ---------------------------------------------------------------------------
# Cell 5 (code): Load modules — the 8 JD modules (perception, triage, etc.)
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 5: Load modules ---",
    "import os, sys, importlib",
    "from pathlib import Path",
    "",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "SRC = REPO / 'src'",
    "",
    "# --- 1. Path setup (idempotent — cell 4 already added REPO/src) ---",
    "for _p in (REPO, REPO / 'notebooks', SRC):",
    "    _sp = str(_p)",
    "    if _sp not in sys.path:",
    "        sys.path.insert(0, _sp)",
    "",
    "# --- 2. Module metadata: toggle key + import path + 1-line description ---",
    "from colab_session import get_state",
    "state = get_state()",
    "",
    "MODULES_META = [",
    "    ('module:perception',             'conveyor_perception.perception',             'UltralyticsDetector + RecyclingInferenceService'),",
    "    ('module:triage',                 'conveyor_perception.triage',                 'L1TriageAgent + 7 severity rules'),",
    "    ('module:predictive_maintenance', 'conveyor_perception.predictive_maintenance', 'MaintenanceAdvisor + 3 signal types'),",
    "    ('module:multitask',              'conveyor_perception.multitask',              'MultitaskPipeline (Detector->Tracker->Drift->Triage)'),",
    "    ('module:integration',            'conveyor_perception.integration',            'ConveyorNode (real ROS 2) + MockROS2Node (CI)'),",
    "    ('module:robustness',             'conveyor_perception.robustness',             'RobustnessTestSuite + 13 augmentations'),",
    "    ('module:monitoring',             'conveyor_perception.monitoring',             'MonitoringDashboard + ShiftReport'),",
    "    ('module:optimization',           'conveyor_perception.optimization',           'benchmark_pytorch/onnx + export_onnx'),",
    "]",
    "",
    "loaded: list = []",
    "skipped: list = []",
    "failed: list = []",
    "",
    "# --- 3. Toggle-gated dynamic load (one bad module doesn't kill the cell) ---",
    "print('  Loading 8 JD modules:')",
    "for _toggle_key, _module_path, _desc in MODULES_META:",
    "    if not state.toggles.get(_toggle_key, True):",
    "        skipped.append(_toggle_key)",
    "        print(f'    ○ {_module_path}  (disabled by toggle)')",
    "        continue",
    "    try:",
    "        importlib.import_module(_module_path)",
    "        loaded.append(_module_path)",
    "        print(f'    ✓ {_module_path}')",
    "        print(f'        {_desc}')",
    "    except Exception as _e:",
    "        failed.append((_module_path, str(_e)))",
    "        print(f'    ✗ {_module_path}  failed: {_e}')",
    "",
    "state.log(",
    "    'cell-5',",
    "    action='load-modules',",
    "    loaded=loaded,",
    "    skipped=skipped,",
    "    failed=[m for m, _ in failed],",
    ")",
    "print()",
    "print(f'  ✓ loaded {len(loaded)}/{len(MODULES_META)} modules, skipped {len(skipped)}, failed {len(failed)}.')",
    "print('  Next: cell 6 (data registry).')",
))


# ---------------------------------------------------------------------------
# Cell 6 (code): Data registry — scan data/sample/ and data/raw/ for datasets
# (YOLO format = directory containing data.yaml). Side-effect-free: just reads.
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 6: Data registry ---",
    "import os, sys, subprocess, json",
    "from pathlib import Path",
    "",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "",
    "# --- 1. Defensive PyYAML install (data.yaml is YAML) ---",
    "try:",
    "    import yaml  # noqa: F401",
    "except ImportError:",
    "    print('  Installing PyYAML (data.yaml parser)...')",
    "    subprocess.check_call(",
    "        [sys.executable, '-m', 'pip', 'install', '-q', '--no-input', 'pyyaml']",
    "    )",
    "    print('  ✓ installed.')",
    "    import yaml",
    "",
    "# --- 2. Path setup (idempotent) ---",
    "SRC = REPO / 'src'",
    "for _p in (REPO, REPO / 'notebooks', SRC):",
    "    _sp = str(_p)",
    "    if _sp not in sys.path:",
    "        sys.path.insert(0, _sp)",
    "",
    "# --- 3. Scan data/ for datasets with data.yaml ---",
    "from colab_session import get_state",
    "state = get_state()",
    "",
    "DATA_ROOTS = [REPO / 'data' / 'sample', REPO / 'data' / 'raw']",
    "",
    "def _count_imgs(_d: Path, _rel_path: str) -> int:",
    "    if not _rel_path:",
    "        return 0",
    "    _p = _d / _rel_path.lstrip('./').lstrip('/')",
    "    if not _p.exists():",
    "        return 0",
    "    return len(list(_p.glob('*.jpg'))) + len(list(_p.glob('*.png')))",
    "",
    "def _dir_size_mb(_d: Path) -> float:",
    "    if not _d.exists():",
    "        return 0.0",
    "    return sum(f.stat().st_size for f in _d.rglob('*') if f.is_file()) / (1024 * 1024)",
    "",
    "registry: list = []",
    "for _root in DATA_ROOTS:",
    "    if not _root.exists():",
    "        continue",
    "    for _d in sorted(_root.iterdir()):",
    "        if not _d.is_dir():",
    "            continue",
    "        _yaml_p = _d / 'data.yaml'",
    "        if not _yaml_p.exists():",
    "            continue",
    "        try:",
    "            _cfg = yaml.safe_load(_yaml_p.read_text())",
    "        except Exception as _e:",
    "            print(f'  ✗ could not parse {_yaml_p}: {_e}')",
    "            _cfg = {}",
    "        _nc = _cfg.get('nc', len(_cfg.get('names', [])))",
    "        _names = _cfg.get('names', [])",
    "        _n_train = _count_imgs(_d, _cfg.get('train', 'train/images'))",
    "        _n_val = _count_imgs(_d, _cfg.get('val', 'val/images'))",
    "        _meta_p = _d / 'dataset_meta.json'",
    "        _meta = json.loads(_meta_p.read_text()) if _meta_p.exists() else {}",
    "        _status = 'bundled' if _root == REPO / 'data' / 'sample' else 'downloaded'",
    "        _size_mb = _dir_size_mb(_d)",
    "        registry.append({",
    "            'name': _d.name,",
    "            'path': str(_d),",
    "            'status': _status,",
    "            'n_train': _n_train,",
    "            'n_val': _n_val,",
    "            'nc': _nc,",
    "            'names': _names,",
    "            'source': _meta.get('source', '—'),",
    "            'license': _meta.get('license', '—'),",
    "            'baseline_mAP50': _meta.get('pre_trained_baseline_mAP50'),",
    "            'size_mb': _size_mb,",
    "        })",
    "",
    "# --- 4. Cache the registry to state (downstream cells read it) ---",
    "state.dataset_registry = registry",
    "state.metric('datasets_available', len(registry))",
    "state.log(",
    "    'cell-6',",
    "    action='data-registry',",
    "    n_datasets=len(registry),",
    "    names=[_r['name'] for _r in registry],",
    ")",
    "",
    "# --- 5. Render as a text table ---",
    "W = 82",
    "print()",
    "print('─' * W)",
    "print(f'  DATA REGISTRY  ({len(registry)} dataset(s) on disk)'.center(W))",
    "print('─' * W)",
    "if not registry:",
    "    print('  (no datasets found — run cell 7 to download the recycling_v3 set)')",
    "else:",
    "    for _r in registry:",
    "        print(f'  • {_r[\"name\"]}  [{_r[\"status\"]}]')",
    "        print(f'      path:    {_r[\"path\"]}')",
    "        print(f'      images:  {_r[\"n_train\"]} train  /  {_r[\"n_val\"]} val  /  {_r[\"size_mb\"]:.1f} MB')",
    "        print(f'      classes ({_r[\"nc\"]}): {\", \".join(str(_n) for _n in _r[\"names\"])}')",
    "        if _r.get('source') and _r['source'] != '—':",
    "            print(f'      source:  {_r[\"source\"]}')",
    "        if _r.get('license') and _r['license'] != '—':",
    "            print(f'      license: {_r[\"license\"]}')",
    "        if _r.get('baseline_mAP50') is not None:",
    "            print(f'      baseline mAP50: {_r[\"baseline_mAP50\"]}')",
    "        print()",
    "print('─' * W)",
    "if registry:",
    "    print(f'  ✓ {len(registry)} dataset(s) registered.  Next: cell 7 (download if you need a bigger one).')",
    "else:",
    "    print('  ✓ registry ready (empty).  Next: cell 7 (download).')",
))


# ---------------------------------------------------------------------------
# Cell 7 (code): Data download — idempotent Roboflow pull for a target dataset.
# Re-running this cell is safe: if the target is already on disk with a valid
# data.yaml, it prints "already on disk" and skips. To get a different dataset,
# change TARGET_NAME below and re-run.
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 7: Data download (idempotent) ---",
    "import os, sys, shutil",
    "from pathlib import Path",
    "from colab_session import get_state",
    "",
    "state = get_state()",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "DATA_RAW = REPO / 'data' / 'raw'",
    "",
    "# Change TARGET_NAME to download a different dataset (or 'skip' to do nothing).",
    "TARGET_NAME = 'recycling_v3'  # 'recycling_v3' | 'everyday_recycle_waste' | 'recycling_classification' | 'skip'",
    "",
    "DATASETS = {",
    "    'recycling_v3':             dict(workspace='zkf624',                       project='-recycling',               version=3),",
    "    'everyday_recycle_waste':   dict(workspace='everyday-recycle-waste-xhayk', project='everyday-recycle-waste',   version=3),",
    "    'recycling_classification': dict(workspace='new-workspace-eosax',          project='recycling-classification', version=1),",
    "}",
    "",
    "SAFE_NAME = TARGET_NAME.replace('-', '_')",
    "TARGET = DATA_RAW / SAFE_NAME",
    "DATA_YAML = TARGET / 'data.yaml'",
    "",
    "def _count_imgs(_p: Path) -> int:",
    "    if not _p.exists():",
    "        return 0",
    "    return len(list(_p.glob('*.jpg'))) + len(list(_p.glob('*.png')))",
    "",
    "def _dir_size_mb(_d: Path) -> float:",
    "    if not _d.exists():",
    "        return 0.0",
    "    return sum(f.stat().st_size for f in _d.rglob('*') if f.is_file()) / (1024 * 1024)",
    "",
    "W = 82",
    "print()",
    "print('─' * W)",
    "print(f'  DOWNLOAD CHECK  —  target: {SAFE_NAME}'.center(W))",
    "print('─' * W)",
    "",
    "if DATA_YAML.exists():",
    "    # 1. Already on disk — skip the download (idempotent re-run path).",
    "    n_train = _count_imgs(TARGET / 'train' / 'images')",
    "    n_val = _count_imgs(TARGET / 'val' / 'images')",
    "    n_test = _count_imgs(TARGET / 'test' / 'images')",
    "    size_mb = _dir_size_mb(TARGET)",
    "    print(f'  ✓ {SAFE_NAME} already on disk — download skipped')",
    "    print()",
    "    print(f'    train:  {n_train:>6} images')",
    "    print(f'    val:    {n_val:>6} images' + (f'   (incl. test: {n_test})' if n_test else ''))",
    "    print(f'    size:   {size_mb:>7.1f} MB on disk')",
    "    print(f'    path:   {TARGET}')",
    "    print('─' * W)",
    "    state.metric(f'dataset_{SAFE_NAME}_status', 'already_present')",
    "    state.metric(f'dataset_{SAFE_NAME}_n_train', n_train)",
    "    state.metric(f'dataset_{SAFE_NAME}_n_val', n_val)",
    "    state.metric(f'dataset_{SAFE_NAME}_size_mb', round(size_mb, 1))",
    "    state.log(",
    "        'cell-7',",
    "        action='skip',",
    "        reason='already-present',",
    "        dataset=SAFE_NAME,",
    "        n_train=n_train,",
    "        n_val=n_val,",
    "        size_mb=round(size_mb, 1),",
    "    )",
    "elif TARGET_NAME == 'skip':",
    "    print('  TARGET_NAME=skip — no download attempted.')",
    "    print('─' * W)",
    "    state.metric('dataset_download_status', 'skipped')",
    "else:",
    "    # 2. Try Roboflow Universe (public demo key, read-only for CC-BY 4.0 datasets).",
    "    cfg = DATASETS.get(SAFE_NAME)",
    "    if cfg is None:",
    "        print(f'  ✗ Unknown dataset: {TARGET_NAME!r}')",
    "        print(f'  Add an entry to DATASETS in this cell, then re-run.')",
    "        print('─' * W)",
    "        state.metric(f'dataset_{SAFE_NAME}_status', 'unknown')",
    "    else:",
    "        print(f'  Downloading {SAFE_NAME} from Roboflow Universe...')",
    "        print(f'    workspace: {cfg[\"workspace\"]}')",
    "        print(f'    project:   {cfg[\"project\"]}')",
    "        print(f'    version:   {cfg[\"version\"]}')",
    "        print('─' * W)",
    "        _ok = False",
    "        _err = None",
    "        try:",
    "            from roboflow import Roboflow",
    "            _api_key = 'qogO5hAuLgUUYMbNT6W3'  # public demo key, read-only",
    "            _env_p = REPO / '.env'",
    "            if _env_p.exists():",
    "                for _line in _env_p.read_text().splitlines():",
    "                    if _line.startswith('ROBOFLOW_API_KEY='):",
    "                        _api_key = _line.split('=', 1)[1].strip() or _api_key",
    "            _rf = Roboflow(api_key=_api_key)",
    "            _project = _rf.workspace(cfg['workspace']).project(cfg['project'])",
    "            _version = _project.version(cfg['version'])",
    "            # 'yolov11' is the Roboflow LABEL format (YOLO .txt annotations",
    "            # + folder layout), NOT the model architecture. The YOLO .txt schema",
    "            # is identical across YOLOv5/8/11/26 — the actual model choice",
    "            # (yolo26s) happens in cell 8 via YOLO('yolo26s.pt').",
    "            _dataset = _version.download('yolov11')",
    "            _downloaded = Path(_dataset.location)",
    "            if _downloaded.exists():",
    "                DATA_RAW.mkdir(parents=True, exist_ok=True)",
    "                if TARGET.exists():",
    "                    shutil.rmtree(TARGET)",
    "                _downloaded.rename(TARGET)",
    "                _ok = True",
    "        except ImportError as _e:",
    "            _err = f'roboflow not installed ({_e})'",
    "        except Exception as _e:",
    "            _err = f'{type(_e).__name__}: {_e}'",
    "",
    "        if _ok:",
    "            n_train = _count_imgs(TARGET / 'train' / 'images')",
    "            n_val = _count_imgs(TARGET / 'val' / 'images')",
    "            size_mb = _dir_size_mb(TARGET)",
    "            print(f'  ✓ Downloaded {SAFE_NAME}')",
    "            print()",
    "            print(f'    train:  {n_train:>6} images')",
    "            print(f'    val:    {n_val:>6} images')",
    "            print(f'    size:   {size_mb:>7.1f} MB on disk')",
    "            print(f'    path:   {TARGET}')",
    "            print('─' * W)",
    "            state.metric(f'dataset_{SAFE_NAME}_status', 'downloaded')",
    "            state.metric(f'dataset_{SAFE_NAME}_n_train', n_train)",
    "            state.metric(f'dataset_{SAFE_NAME}_n_val', n_val)",
    "            state.metric(f'dataset_{SAFE_NAME}_size_mb', round(size_mb, 1))",
    "            state.log(",
    "                'cell-7',",
    "                action='downloaded',",
    "                dataset=SAFE_NAME,",
    "                n_train=n_train,",
    "                n_val=n_val,",
    "                size_mb=round(size_mb, 1),",
    "            )",
    "        else:",
    "            print(f'  ✗ Download failed: {_err}')",
    "            print()",
    "            print('  Manual fallback:')",
    "            print(f'    1. Open https://universe.roboflow.com/{cfg[\"workspace\"]}/{cfg[\"project\"]}/dataset/{cfg[\"version\"]}')",
    "            print('    2. Click Download Dataset -> Format: YOLOv11')",
    "            print(f'    3. Extract the zip into {DATA_RAW}/ so the path is:')",
    "            print(f'       {DATA_RAW}/{SAFE_NAME}/data.yaml')",
    "            print('─' * W)",
    "            state.metric(f'dataset_{SAFE_NAME}_status', 'failed')",
    "            state.log('cell-7', action='download-failed', error=str(_err), dataset=SAFE_NAME)",
    "",
    "# 3. Refresh the registry on state (so cell 8 sees the new dataset).",
    "import yaml as _yaml",
    "# 3a. v1.5 fix: ensure each downloaded dataset has a real val split.",
    "# The recycling_v3 Roboflow download gives valid/ = 0 images, which makes",
    "# mAP50 computed on an empty set (always 1.0). _ensure_val_split moves",
    "# 10% of train -> valid so the metric is real. Idempotent — no-op if",
    "# valid/ already has >= 50 images.",
    "from colab_session import _ensure_val_split",
    "for _d in [REPO / 'data' / 'sample' / 'recycling_demo', REPO / 'data' / 'raw' / 'recycling_v3']:",
    "    if (_d / 'data.yaml').exists():",
    "        _n_v = _ensure_val_split(_d, val_fraction=0.1, min_val_images=50, seed=42)",
    "        if _n_v > 0:",
    "            print(f'  val split ensured for {_d.name}: {_n_v} images in valid/')",
    "_registry = []",
    "for _root in [REPO / 'data' / 'sample', REPO / 'data' / 'raw']:",
    "    if not _root.exists():",
    "        continue",
    "    for _d in sorted(_root.iterdir()):",
    "        if not _d.is_dir():",
    "            continue",
    "        _yp = _d / 'data.yaml'",
    "        if not _yp.exists():",
    "            continue",
    "        try:",
    "            _cfg = _yaml.safe_load(_yp.read_text())",
    "        except Exception:",
    "            _cfg = {}",
    "        _nc = _cfg.get('nc', len(_cfg.get('names', [])))",
    "        _names = _cfg.get('names', [])",
    "        _n_train = _count_imgs(_d / _cfg.get('train', 'train/images').lstrip('./').lstrip('/'))",
    "        _n_val = _count_imgs(_d / _cfg.get('val', 'val/images').lstrip('./').lstrip('/'))",
    "        _status = 'bundled' if _root == REPO / 'data' / 'sample' else 'downloaded'",
    "        _size_mb = _dir_size_mb(_d)",
    "        _registry.append({",
    "            'name': _d.name,",
    "            'path': str(_d),",
    "            'status': _status,",
    "            'n_train': _n_train,",
    "            'n_val': _n_val,",
    "            'nc': _nc,",
    "            'names': _names,",
    "            'size_mb': _size_mb,",
    "        })",
    "state.dataset_registry = _registry",
    "state.metric('datasets_available', len(_registry))",
    "print()",
    "print(f'  ✓ {len(_registry)} dataset(s) now in registry.  Next: cell 8 (train).')",
))


# ---------------------------------------------------------------------------
# Cell 8 (code): Train — YOLO26s on the selected dataset, CACHED on re-run.
# If models/{DATASET_NAME}/weights/best.pt + results.csv already exist, the
# cached metrics are read and reported (no re-training). To force a retrain,
# delete models/{DATASET_NAME}/ and re-run this cell.
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 8: Train (cached on re-run) ---",
    "import os, sys, time, csv",
    "from pathlib import Path",
    "from colab_session import get_state, pick_device",
    "",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "state = get_state()",
    "",
    "# --- 0. Pick the dataset (change DATASET_NAME to switch) ---",
    "DATASET_NAME = 'recycling_demo'  # 'recycling_demo' (bundled, ~1 min) or 'recycling_v3' (downloaded, ~5-10 min)",
    "",
    "# --- 1. Resolve the dataset path from the registry (or fall back to disk scan) ---",
    "_reg = getattr(state, 'dataset_registry', None) or []",
    "_match = next((_r for _r in _reg if _r['name'] == DATASET_NAME), None)",
    "if _match is None:",
    "    for _root in [REPO / 'data' / 'sample', REPO / 'data' / 'raw']:",
    "        _cand = _root / DATASET_NAME",
    "        if (_cand / 'data.yaml').exists():",
    "            _match = {'name': DATASET_NAME, 'path': str(_cand), 'n_train': 0, 'n_val': 0, 'nc': 0, 'names': []}",
    "            break",
    "",
    "# --- 2. Compute the cache + toggle gate (skip = don't crash) ---",
    "_skip_reason = None",
    "if not state.toggles.get('module:perception', True):",
    "    _skip_reason = 'toggle-off'",
    "elif _match is None:",
    "    _skip_reason = 'dataset-not-found'",
    "",
    "if _skip_reason:",
    "    print('─' * 72)",
    "    if _skip_reason == 'toggle-off':",
    "        print('  module:perception toggle is OFF — skipping training.')",
    "        print('  Re-enable the toggle in cell 3 to train the model.')",
    "    else:",
    "        print(f'  ✗ Dataset {DATASET_NAME!r} not found in registry or on disk.')",
    "        print('  Run cell 6 to scan, or cell 7 to download.')",
    "    print('─' * 72)",
    "    state.log('cell-8', action='skipped', reason=_skip_reason, dataset=DATASET_NAME)",
    "    print('  Next: cell 9 (compare).')",
    "else:",
    "    DATA_DIR = Path(_match['path'])",
    "    YAML_P = DATA_DIR / 'data.yaml'",
    "    MODEL_DIR = REPO / 'models' / DATASET_NAME",
    "    BEST_PT = MODEL_DIR / 'weights' / 'best.pt'",
    "    RESULTS_CSV = MODEL_DIR / 'results.csv'",
    "",
    "    print('─' * 72)",
    "    _n_train = _match.get('n_train', 0) or 0",
    "    _n_val = _match.get('n_val', 0) or 0",
    "    _nc = _match.get('nc', 0) or 0",
    "    print(f'  TRAIN  —  dataset: {DATASET_NAME}  (train: {_n_train}, val: {_n_val}, cls: {_nc})'.center(72))",
    "    print('─' * 72)",
    "",
    "    if BEST_PT.exists() and RESULTS_CSV.exists():",
    "        # --- Cached path: read metrics from results.csv, no re-training ---",
    "        print(f'  ✓ Cached model found at {BEST_PT}')",
    "        print(f'      size: {BEST_PT.stat().st_size / 1e6:.1f} MB')",
    "        try:",
    "            with open(RESULTS_CSV) as _f:",
    "                _rows = list(csv.DictReader(_f))",
    "                _rows = [_r for _r in _rows if any(v.strip() for v in _r.values())]",
    "            if _rows:",
    "                _last = _rows[-1]",
    "                _strip = lambda _k: _last.get(_k, '').strip()",
    "                print()",
    "                print('  -- Final epoch metrics (from results.csv) --')",
    "                for _k in [",
    "                    'epoch', 'train/box_loss', 'train/cls_loss', 'train/dfl_loss',",
    "                    'metrics/precision(B)', 'metrics/recall(B)',",
    "                    'metrics/mAP50(B)', 'metrics/mAP50-95(B)', 'lr/pg0',",
    "                ]:",
    "                    if _k in _last:",
    "                        print(f'      {_k:30}  {_strip(_k)}')",
    "                try:",
    "                    _map50 = float(_strip('metrics/mAP50(B)'))",
    "                    state.metric(f'map50_{DATASET_NAME}', _map50)",
    "                    state.active_model_path = str(BEST_PT)",
    "                    state.active_dataset = DATASET_NAME",
    "                    state.log('cell-8', action='cached', dataset=DATASET_NAME, mAP50=_map50)",
    "                except Exception:",
    "                    pass",
    "        except Exception as _e:",
    "            print(f'  could not read results.csv: {_e}')",
    "        print()",
    "        print(f'  re-run skipped: cached model used. (delete {MODEL_DIR} to retrain.)')",
    "        print('─' * 72)",
    "    else:",
    "        # --- Fresh path: actually train ---",
    "        print(f'  No cached model — training YOLO26s on {DATASET_NAME}...')",
    "        print('  (first run on a dataset: 1-15 min depending on size; later runs are cached)')",
    "        t0 = time.time()",
    "        try:",
    "            from ultralytics import YOLO",
    "            import torch",
    "            device = pick_device()",
    "            gpu_name = torch.cuda.get_device_name(0) if device == '0' else 'cpu'",
    "            print(f'  device: {device} ({gpu_name})')",
    "            print(f'  data.yaml: {YAML_P}')",
    "",
    "            _epochs = 8 if _n_train < 200 else 30",
    "            print(f'  epochs: {_epochs}  (auto-sized for {_n_train} train images)')",
    "",
    "            model = YOLO('yolo26s.pt')",
    "            # patience=3 (not the Ultralytics default of 15): for short runs",
    "            # like our 8-epoch demo on recycling_demo, patience=15 never fires",
    "            # because the epoch cutoff happens first. patience=3 gives early",
    "            # stopping teeth on small data while still being forgiving on",
    "            # 30-epoch runs on recycling_v3.",
    "            model.train(",
    "                data=str(YAML_P),",
    "                epochs=_epochs,",
    "                imgsz=640,",
    "                batch=16,",
    "                device=device,",
    "                project=str(MODEL_DIR.parent),",
    "                name=DATASET_NAME,",
    "                exist_ok=True,",
    "                patience=3,",
    "                verbose=True,",
    "                plots=False,",
    "            )",
    "            train_time = time.time() - t0",
    "            state.metric(f'train_time_{DATASET_NAME}', round(train_time, 1))",
    "            print(f'\\n  Training complete in {train_time/60:.1f} min')",
    "            if BEST_PT.exists():",
    "                print(f'    best.pt: {BEST_PT} ({BEST_PT.stat().st_size / 1e6:.1f} MB)')",
    "                state.active_model_path = str(BEST_PT)",
    "                state.active_dataset = DATASET_NAME",
    "                try:",
    "                    with open(RESULTS_CSV) as _f:",
    "                        _last = list(csv.DictReader(_f))[-1]",
    "                    _map50 = float(_last.get('metrics/mAP50(B)', '0').strip())",
    "                    state.metric(f'map50_{DATASET_NAME}', _map50)",
    "                    print(f'    mAP50: {_map50:.3f}')",
    "                    state.log(",
    "                        'cell-8',",
    "                        action='trained',",
    "                        dataset=DATASET_NAME,",
    "                        mAP50=_map50,",
    "                        train_time=round(train_time, 1),",
    "                    )",
    "                except Exception as _e:",
    "                    print(f'    (could not read final mAP from results.csv: {_e})')",
    "                    state.log(",
    "                        'cell-8',",
    "                        action='trained',",
    "                        dataset=DATASET_NAME,",
    "                        train_time=round(train_time, 1),",
    "                    )",
    "        except Exception as _e:",
    "            print(f'  ✗ Training failed: {type(_e).__name__}: {_e}')",
    "            state.log(",
    "                'cell-8',",
    "                action='failed',",
    "                reason='training-error',",
    "                error=str(_e),",
    "                dataset=DATASET_NAME,",
    "            )",
    "        print()",
    "        print('─' * 72)",
    "        print('  Trained. To re-run for cached output, re-run this cell.')",
    "        print(f'  To force retrain:  !rm -rf {MODEL_DIR}  then re-run this cell.')",
    "        print('─' * 72)",
    "    print('  Next: cell 9 (compare).')",
))


# ---------------------------------------------------------------------------
# Cell 9 (code): Compare — side-by-side metrics for every trained model in
# models/. Scans for subdirs with both best.pt + results.csv, reads the final
# epoch metrics, renders a text table, and (if matplotlib is available) a bar
# chart. The "best mAP50" row is highlighted + promoted to active model.
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 9: Compare trained models (side-by-side) ---",
    "import csv",
    "from pathlib import Path",
    "from colab_session import get_state",
    "",
    "state = get_state()",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "MODELS_ROOT = REPO / 'models'",
    "",
    "W = 100",
    "print('─' * W)",
    "print(f'  MODEL COMPARISON  (side-by-side metrics)'.center(W))",
    "print('─' * W)",
    "",
    "rows: list = []",
    "if MODELS_ROOT.exists():",
    "    for _md in sorted(MODELS_ROOT.iterdir()):",
    "        if not _md.is_dir():",
    "            continue",
    "        _best_pt = _md / 'weights' / 'best.pt'",
    "        _results_csv = _md / 'results.csv'",
    "        if not (_best_pt.exists() and _results_csv.exists()):",
    "            continue",
    "        try:",
    "            with open(_results_csv) as _f:",
    "                _csv_rows = [r for r in csv.DictReader(_f) if any(v.strip() for v in r.values())]",
    "            if not _csv_rows:",
    "                continue",
    "            _last = _csv_rows[-1]",
    "            _s = lambda _k: _last.get(_k, '').strip()",
    "            rows.append({",
    "                'name': _md.name,",
    "                'path': str(_best_pt),",
    "                'size_mb': _best_pt.stat().st_size / 1e6,",
    "                'epochs': _s('epoch'),",
    "                'precision': _s('metrics/precision(B)'),",
    "                'recall': _s('metrics/recall(B)'),",
    "                'mAP50': _s('metrics/mAP50(B)'),",
    "                'mAP50_95': _s('metrics/mAP50-95(B)'),",
    "            })",
    "        except Exception as _e:",
    "            print(f'  could not read {_md.name}: {_e}')",
    "",
    "if not rows:",
    "    print('  No trained models found. Run cell 8 at least once.')",
    "    state.log('cell-9', action='empty', reason='no-models')",
    "else:",
    "    print(f'  {\"NAME\":18}  {\"SIZE\":>6}  {\"EPOCHS\":>6}  {\"P\":>7}  {\"R\":>7}  {\"mAP50\":>7}  {\"mAP50-95\":>9}')",
    "    print('─' * W)",
    "    for _r in rows:",
    "        print(f'  {_r[\"name\"]:18}  {_r[\"size_mb\"]:>5.1f}M  {_r[\"epochs\"]:>6}  '",
    "              f'{_r[\"precision\"]:>7}  {_r[\"recall\"]:>7}  {_r[\"mAP50\"]:>7}  {_r[\"mAP50_95\"]:>9}')",
    "    print('─' * W)",
    "",
    "    if len(rows) >= 2:",
    "        _best = max(rows, key=lambda _r: float(_r['mAP50']) if _r['mAP50'] else 0)",
    "        print(f'  Best mAP50:  {_best[\"name\"]}  ({_best[\"mAP50\"]})')",
    "        # Promote the best model to active_model_path so downstream cells use it.",
    "        state.active_model_path = _best['path']",
    "        state.active_dataset = _best['name']",
    "        state.metric('best_mAP50_model', _best['name'])",
    "        state.metric('best_mAP50_value', float(_best['mAP50']))",
    "    elif len(rows) == 1:",
    "        _only = rows[0]",
    "        print(f'  Only 1 model: {_only[\"name\"]}  (mAP50={_only[\"mAP50\"]})')",
    "        state.active_model_path = _only['path']",
    "        state.active_dataset = _only['name']",
    "        state.metric('best_mAP50_model', _only['name'])",
    "        if _only['mAP50']:",
    "            state.metric('best_mAP50_value', float(_only['mAP50']))",
    "    print('─' * W)",
    "",
    "    state.log(",
    "        'cell-9',",
    "        action='compare',",
    "        n_models=len(rows),",
    "        names=[_r['name'] for _r in rows],",
    "    )",
    "",
    "    # Optional bar chart (matplotlib is a Colab standard dep; defensive try/except).",
    "    try:",
    "        import matplotlib",
    "        matplotlib.use('Agg')",
    "        import matplotlib.pyplot as plt",
    "        _names = [_r['name'] for _r in rows]",
    "        _map50 = [float(_r['mAP50']) if _r['mAP50'] else 0 for _r in rows]",
    "        _map50_95 = [float(_r['mAP50_95']) if _r['mAP50_95'] else 0 for _r in rows]",
    "        _x = list(range(len(rows)))",
    "        _w = 0.35",
    "        _fig, _ax = plt.subplots(figsize=(7, 4))",
    "        _b1 = _ax.bar([_i - _w/2 for _i in _x], _map50, _w, label='mAP50', color='#22C55E')",
    "        _b2 = _ax.bar([_i + _w/2 for _i in _x], _map50_95, _w, label='mAP50-95', color='#3B82F6')",
    "        _ax.set_xticks(_x)",
    "        _ax.set_xticklabels(_names, rotation=20, ha='right')",
    "        _ax.set_ylabel('mAP')",
    "        _ax.set_ylim(0, 1.0)",
    "        _ax.set_title('Trained models — mAP comparison')",
    "        _ax.legend()",
    "        _ax.grid(axis='y', alpha=0.3)",
    "        for _bar in list(_b1) + list(_b2):",
    "            _h = _bar.get_height()",
    "            _ax.text(_bar.get_x() + _bar.get_width()/2, _h + 0.01, f'{_h:.2f}', ha='center', fontsize=9)",
    "        plt.tight_layout()",
    "        _chart_path = REPO / 'comparison.png'",
    "        plt.savefig(str(_chart_path), dpi=100)",
    "        print(f'  chart saved to {_chart_path}')",
    "    except ImportError:",
    "        print('  (matplotlib not available — text table is the source of truth)')",
    "    except Exception as _e:",
    "        print(f'  (chart skipped: {type(_e).__name__}: {_e})')",
    "",
    "print()",
    "print('  ✓ compare done.  Next: cell 10 (pipeline).')",
))


# ---------------------------------------------------------------------------
# Cell 10 (code): Pipeline — assemble Detector→Tracker→Drift→Triage→Maintenance
# from the 4 abstractions (cell 4) + the 8 modules (cell 5), using the
# best-trained model (state.active_model_path from cell 9). Run a small batch
# of frames to populate drift signals, then report timing + detection count.
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 10: Pipeline (Detector→Tracker→Drift→Triage→Maintenance) ---",
    "import os, sys, time",
    "from pathlib import Path",
    "from colab_session import get_state, pick_device",
    "",
    "state = get_state()",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "SRC = REPO / 'src'",
    "",
    "# Idempotent path setup (REPO + REPO/notebooks + REPO/src)",
    "for _p in (REPO, REPO / 'notebooks', SRC):",
    "    _sp = str(_p)",
    "    if _sp not in sys.path:",
    "        sys.path.insert(0, _sp)",
    "",
    "W = 82",
    "print('─' * W)",
    "print('  PIPELINE  (Detector→Tracker→Drift→Triage→Maintenance)'.center(W))",
    "print('─' * W)",
    "",
    "# --- 0. Skip if no active model or toggle off ---",
    "_skip_reason = None",
    "if not getattr(state, 'active_model_path', None):",
    "    _skip_reason = 'no-model'",
    "elif not Path(state.active_model_path).exists():",
    "    _skip_reason = 'model-missing'",
    "elif not state.toggles.get('module:multitask', True):",
    "    _skip_reason = 'toggle-off'",
    "",
    "if _skip_reason:",
    "    if _skip_reason == 'no-model':",
    "        print('  No active model. Run cell 8 to train (cell 9 picks the best).')",
    "    elif _skip_reason == 'model-missing':",
    "        print(f'  Active model missing: {state.active_model_path}')",
    "        print('  Re-run cell 8 to re-train.')",
    "    else:",
    "        print('  module:multitask toggle is OFF — skipping pipeline.')",
    "        print('  Re-enable the toggle in cell 3 to run the pipeline.')",
    "    print('─' * W)",
    "    state.log('cell-10', action='skipped', reason=_skip_reason)",
    "    print('  Next: cell 11 (visual analytics).')",
    "else:",
    "    print(f'  Active model:   {Path(state.active_model_path).name}')",
    "    print(f'  Active dataset: {getattr(state, \"active_dataset\", \"?\")}')",
    "    print('  Assembling the 5 components...')",
    "    print('─' * W)",
    "",
    "    try:",
    "        # --- 1. Load the detector with the active model ---",
    "        from ultralytics import YOLO",
    "        from conveyor_perception.perception.ultralytics_detector import UltralyticsDetector",
    "",
    "        _yolo = YOLO(state.active_model_path)",
    "        _resolved_path = _yolo.ckpt_path or state.active_model_path",
    "        _names_obj = getattr(_yolo, 'names', None)",
    "        _class_names = list(_names_obj.values()) if _names_obj else \\",
    "            ['Glass', 'metal', 'plastic', 'vinyl']",
    "        det = UltralyticsDetector(",
    "            model_path=_resolved_path,",
    "            class_names=_class_names,",
    "            conf_threshold=0.25,",
    "            device=pick_device(),",
    "            imgsz=640,",
    "        )",
    "        print(f'  ✓ Detector    loaded (model: {Path(_resolved_path).name}, classes: {len(_class_names)})')",
    "",
    "        # --- 2. Wire up the other 4 components ---",
    "        from conveyor_perception.core.tracking_pipeline import TrackingPipeline",
    "        from conveyor_perception.core.drift_monitor import DriftMonitor",
    "        from conveyor_perception.triage.agent import L1TriageAgent",
    "        from conveyor_perception.predictive_maintenance.advisor import MaintenanceAdvisor",
    "        from conveyor_perception.multitask.pipeline import MultitaskPipeline",
    "",
    "        tracker = TrackingPipeline()",
    "        print('  ✓ Tracker     loaded (ByteTrack)')",
    "",
    "        drift = DriftMonitor(baseline_window=50, min_samples_for_drift=20)",
    "        print('  ✓ Drift       loaded (KS + z-score + MAD)')",
    "",
    "        triage = L1TriageAgent()",
    "        print('  ✓ Triage      loaded (7 severity rules)')",
    "",
    "        advisor = MaintenanceAdvisor()",
    "        print('  ✓ Maintenance loaded (3 signal types)')",
    "",
    "        # --- 3. Build the pipeline ---",
    "        pipeline = MultitaskPipeline(det, tracker, drift, triage)",
    "        print('─' * W)",
    "        print('  Pipeline assembled: frame → Detector → Tracker → Drift → Triage')",
    "        print('─' * W)",
    "",
    "        # --- 4. Get a sample image (recycling val first, else synthetic) ---",
    "        _sample_path = None",
    "        _val_dir = REPO / 'data' / 'sample' / 'recycling_demo' / 'val' / 'images'",
    "        if _val_dir.exists():",
    "            _cands = sorted(_val_dir.glob('*.jpg'))",
    "            if _cands:",
    "                _sample_path = str(_cands[0])",
    "        if not _sample_path:",
    "            import numpy as np",
    "            import cv2",
    "            _syn = REPO / 'data' / 'sample' / '_synthetic_frame.jpg'",
    "            _syn.parent.mkdir(parents=True, exist_ok=True)",
    "            cv2.imwrite(str(_syn), np.zeros((640, 640, 3), dtype=np.uint8))",
    "            _sample_path = str(_syn)",
    "        import cv2",
    "        _img = cv2.imread(_sample_path)",
    "        if _img is None:",
    "            raise RuntimeError(f'could not read sample image at {_sample_path}')",
    "        print(f'  Sample: {Path(_sample_path).name}  shape={_img.shape}')",
    "",
    "        # --- 5. Run N frames to populate drift signals ---",
    "        N_FRAMES = 10",
    "        print(f'\\n  Running {N_FRAMES} frames through the pipeline...')",
    "        t0 = time.perf_counter()",
    "        _last = None",
    "        for _i in range(N_FRAMES):",
    "            _last = pipeline.step(_img)",
    "        _elapsed_ms = (time.perf_counter() - t0) * 1000",
    "        _ms_per_frame = _elapsed_ms / N_FRAMES",
    "",
    "        state.metric('t4_inference_ms', round(_ms_per_frame, 2))",
    "        state.metric('pipeline_frames', N_FRAMES)",
    "        state.metric('pipeline_total_ms', round(_elapsed_ms, 1))",
    "",
    "        print(f'\\n  ✓ Pipeline ran {N_FRAMES} frames in {_elapsed_ms/1000:.1f}s ({_ms_per_frame:.1f} ms/frame on T4)')",
    "        print(f'      last frame: {len(_last.detections)} detections, {len(_last.alerts)} alerts')",
    "",
    "        state.log(",
    "            'cell-10',",
    "            action='ran',",
    "            dataset=getattr(state, 'active_dataset', None),",
    "            ms_per_frame=round(_ms_per_frame, 2),",
    "            n_detections=len(_last.detections),",
    "            n_alerts=len(_last.alerts),",
    "        )",
    "    except Exception as _e:",
    "        print(f'  ✗ Pipeline failed: {type(_e).__name__}: {_e}')",
    "        state.log(",
    "            'cell-10',",
    "            action='failed',",
    "            error=str(_e),",
    "        )",
    "    print('─' * W)",
    "    print('  Next: cell 11 (visual analytics).')",
))


# ---------------------------------------------------------------------------
# Cell 11 (code): Visual Analytics — the supervision annotator layer.
# Runs inference on a recycling val image, applies the modern annotators
# (RoundBox, RichLabel, HeatMap, PolygonZone, LineZone), saves the result,
# and displays it inline. Uses supervision==0.30.0 API (roundness=, opacity=,
# not border_radius= or alpha=).
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 11: Visual Analytics (the impressive part) ---",
    "import os, sys, time",
    "from pathlib import Path",
    "from colab_session import get_state, pick_device",
    "",
    "state = get_state()",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "SRC = REPO / 'src'",
    "",
    "# Idempotent path setup",
    "for _p in (REPO, REPO / 'notebooks', SRC):",
    "    _sp = str(_p)",
    "    if _sp not in sys.path:",
    "        sys.path.insert(0, _sp)",
    "",
    "W = 82",
    "print('─' * W)",
    "print('  VISUAL ANALYTICS  (modern supervision annotators)'.center(W))",
    "print('─' * W)",
    "",
    "# --- 0. Skip if no active model ---",
    "_skip_reason = None",
    "if not getattr(state, 'active_model_path', None):",
    "    _skip_reason = 'no-model'",
    "elif not Path(state.active_model_path).exists():",
    "    _skip_reason = 'model-missing'",
    "else:",
    "    try:",
    "        import supervision as sv  # noqa: F401",
    "    except ImportError:",
    "        _skip_reason = 'supervision-missing'",
    "",
    "if _skip_reason:",
    "    if _skip_reason == 'no-model':",
    "        print('  No active model. Run cell 8 to train, then cell 9.')",
    "    elif _skip_reason == 'model-missing':",
    "        print(f'  Active model missing: {state.active_model_path}')",
    "    else:",
    "        print('  supervision not installed. Re-run cell 2.')",
    "    print('─' * W)",
    "    state.log('cell-11', action='skipped', reason=_skip_reason)",
    "    print('  Next: cell 12 (production path).')",
    "else:",
    "    try:",
    "        import numpy as np",
    "        import cv2",
    "        import supervision as sv",
    "        from IPython.display import display",
    "        from PIL import Image as PILImage",
    "        from collections import Counter",
    "        from ultralytics import YOLO",
    "        from conveyor_perception.perception.ultralytics_detector import UltralyticsDetector",
    "",
    "        # --- 1. Load the detector with the active model ---",
    "        _yolo = YOLO(state.active_model_path)",
    "        _resolved_path = _yolo.ckpt_path or state.active_model_path",
    "        _names_obj = getattr(_yolo, 'names', None)",
    "        _class_names = list(_names_obj.values()) if _names_obj else \\",
    "            ['Glass', 'metal', 'plastic', 'vinyl']",
    "        det = UltralyticsDetector(",
    "            model_path=_resolved_path,",
    "            class_names=_class_names,",
    "            conf_threshold=0.25,",
    "            device=pick_device(),",
    "            imgsz=640,",
    "        )",
    "        print(f'  Detector: {Path(_resolved_path).name}  (classes: {_class_names})')",
    "",
    "        # --- 2. Pick a real recycling val image (sorted, deterministic) ---",
    "        _val_dir = REPO / 'data' / 'sample' / 'recycling_demo' / 'val' / 'images'",
    "        _val_imgs = sorted(_val_dir.glob('*.jpg')) if _val_dir.exists() else []",
    "        if _val_imgs:",
    "            _sample_path = str(_val_imgs[0])",
    "            print(f'  Sample: {_val_imgs[0].name}  (recycling val set)')",
    "        else:",
    "            _syn = REPO / 'data' / 'sample' / '_synthetic_frame.jpg'",
    "            _syn.parent.mkdir(parents=True, exist_ok=True)",
    "            cv2.imwrite(str(_syn), np.zeros((640, 640, 3), dtype=np.uint8))",
    "            _sample_path = str(_syn)",
    "            print('  Sample: _synthetic_frame.jpg  (recycling val missing)')",
    "        _img = cv2.imread(_sample_path)",
    "        _H, _W = _img.shape[:2]",
    "",
    "        # --- 3. Run inference → sv.Detections ---",
    "        _raw = det.detect(_img)",
    "        if _raw:",
    "            dets = sv.Detections(",
    "                xyxy=np.array([d.bbox for d in _raw], dtype=np.float32),",
    "                confidence=np.array([d.confidence for d in _raw], dtype=np.float32),",
    "                class_id=np.array([d.class_id for d in _raw], dtype=int),",
    "            )",
    "        else:",
    "            dets = sv.Detections.empty()",
    "        state.metric('visual_inference_count', len(dets))",
    "        print(f'  ✓ {len(dets)} detections on the sample image')",
    "        if _raw:",
    "            _counts = Counter(d.class_name for d in _raw)",
    "            print('      ' + ' · '.join(f'{n} {name}' for name, n in _counts.most_common()))",
    "",
    "        # --- 4. Annotators (supervision==0.30.0 API) ---",
    "        from supervision.draw.color import ColorPalette",
    "        _rbox = sv.RoundBoxAnnotator(roundness=0.6, color=ColorPalette.DEFAULT)",
    "        _rich = sv.RichLabelAnnotator(color=ColorPalette.DEFAULT, border_radius=4)",
    "        _heat = sv.HeatMapAnnotator(opacity=0.5, radius=30)",
    "",
    "        # Spatial zone: infeed = left 30% of the frame",
    "        _zone = sv.PolygonZone(",
    "            polygon=np.array([[0, 0], [int(_W*0.3), 0], [int(_W*0.3), _H], [0, _H]]),",
    "        )",
    "        _zone_annot = sv.PolygonZoneAnnotator(zone=_zone, color=sv.Color.GREEN, thickness=2)",
    "",
    "        # Throughput line: vertical line in the middle",
    "        _line = sv.LineZone(",
    "            start=sv.Point(x=_W//2, y=0), end=sv.Point(x=_W//2, y=_H),",
    "        )",
    "        _line_annot = sv.LineZoneAnnotator(color=sv.Color.RED, text_scale=1.5)",
    "",
    "        # --- 5. Annotate + display + save ---",
    "        _ann = _img.copy()",
    "        _ann = _heat.annotate(_ann, dets)",
    "        _ann = _rbox.annotate(_ann, dets)",
    "        _labels = [f'{d.class_name} {d.confidence:.2f}' for d in _raw] if _raw else []",
    "        _ann = _rich.annotate(_ann, dets, labels=_labels)",
    "        _ann = _zone_annot.annotate(_ann)",
    "        _cross_in, _cross_out = _line.trigger(dets)",
    "        _ann = _line_annot.annotate(_ann, _line)",
    "",
    "        # Save to disk for the summary cell to pick up",
    "        _out_path = REPO / 'visual_analytics.png'",
    "        cv2.imwrite(str(_out_path), _ann)",
    "        print(f'  saved annotated image: {_out_path.name}')",
    "",
    "        # Display inline (BGR → RGB)",
    "        _ann_rgb = cv2.cvtColor(_ann, cv2.COLOR_BGR2RGB)",
    "        display(PILImage.fromarray(_ann_rgb))",
    "",
    "        # --- 6. Real FPS via supervision.FPSMonitor ---",
    "        # sv.FPSMonitor.tick() is a manual stopwatch — the actual work",
    "        # being measured MUST be inside the tick loop, otherwise the FPS",
    "        # reads how fast the loop runs (~1.9M FPS), not how fast the model",
    "        # runs (~25-40 FPS on T4).",
    "        _fps = sv.FPSMonitor()",
    "        for _ in range(30):",
    "            _fps.tick()",
    "            det.detect(_img)  # <-- the actual work being measured",
    "        state.metric('t4_measured_fps', round(_fps.fps, 1))",
    "        print(f'\\n  ✓ Measured: {_fps.fps:.1f} FPS  (supervision.FPSMonitor)')",
    "        _n_in = int(_cross_in.sum()) if hasattr(_cross_in, 'sum') else int(_cross_in)",
    "        _n_out = int(_cross_out.sum()) if hasattr(_cross_out, 'sum') else int(_cross_out)",
    "        print(f'      LineZone: in={_n_in}  out={_n_out}  (items crossing mid-line)')",
    "",
    "        state.log(",
    "            'cell-11',",
    "            action='ran',",
    "            dataset=getattr(state, 'active_dataset', None),",
    "            n_detections=len(dets),",
    "            fps=round(_fps.fps, 1),",
    "            line_in=_n_in,",
    "            line_out=_n_out,",
    "        )",
    "    except Exception as _e:",
    "        print(f'  ✗ Visual analytics failed: {type(_e).__name__}: {_e}')",
    "        state.log(",
    "            'cell-11',",
    "            action='failed',",
    "            error=str(_e),",
    "        )",
    "    print('─' * W)",
    "    print('  Next: cell 12 (production path).')",
))


# ---------------------------------------------------------------------------
# Cell 12 (code): Production path — Roboflow Hosted Inference API.
# Same model family, different runtime. The Ultralytics local runtime
# (cells 10/11) is what ships when the device has a GPU. The Roboflow
# Hosted API is what ships when edge compute is constrained (camera +
# thin client, or cloud-backed inference).
#
# v3.5.1 fix: the v3.5 cell 12 used to gate everything on the `inference`
# library being importable. The library's deps conflict with our pinned
# `numpy<2.0` + `supervision>=0.30`, so most users saw the OPTIONAL
# skip message and their `ROBOFLOW_MODEL_ID` was never used. v3.5.1
# reads both keys at the top, tries the Hosted API (no library needed,
# uses urllib.request) first, then falls back to the local library.
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 12: Production path (Roboflow Hosted API + optional local lib) ---",
    "import os, sys, time, base64, json",
    "from pathlib import Path",
    "from colab_session import get_state",
    "",
    "state = get_state()",
    "IN_COLAB = \'google.colab\' in sys.modules",
    "REPO = Path(\'/content/conveyor-perception\' if IN_COLAB else \'.\').resolve()",
    "",
    "W = 82",
    "print(\'─\' * W)",
    "print(\'  PRODUCTION PATH  (Roboflow Hosted API + optional local lib)\'.center(W))",
    "print(\'─\' * W)",
    "print(\'  Same YOLO model, different runtime. Local: cells 10/11. Hosted: this cell.\')",
    "print()",
    "",
    "# --- 0. Read both Roboflow keys (ALWAYS, before any inference import) ---",
    "# Priority: userdata (Colab) -> os.environ (local) -> placeholder.",
    "# \'yolov8n-640\' is the Roboflow Hosted COCO YOLOv8n foundation model (public, no key needed).",
    "# For your uploaded recycling_v3: set ROBOFLOW_MODEL_ID + ROBOFLOW_API_KEY in Colab secrets.",
    "_model_id = \'yolov8n-640\'",
    "_api_key = None",
    "try:",
    "    if IN_COLAB:",
    "        from google.colab import userdata as _userdata",
    "        _id = _userdata.get(\'ROBOFLOW_MODEL_ID\')",
    "        if _id:",
    "            _model_id = _id",
    "        _key = _userdata.get(\'ROBOFLOW_API_KEY\')",
    "        if _key:",
    "            _api_key = _key",
    "    else:",
    "        _id = os.environ.get(\'ROBOFLOW_MODEL_ID\')",
    "        if _id:",
    "            _model_id = _id",
    "        _key = os.environ.get(\'ROBOFLOW_API_KEY\')",
    "        if _key:",
    "            _api_key = _key",
    "except Exception:",
    "    pass",
    "",
    "if _model_id != \'yolov8n-640\':",
    "    print(f\'  Loading your uploaded model: {_model_id}  (via Roboflow Hosted API)\')",
    "else:",
    "    print(f\'  Loading foundation model: {_model_id}  (COCO YOLOv8n, public, no key needed)\')",
    "    print(\'  For your uploaded recycling_v3: set ROBOFLOW_MODEL_ID + ROBOFLOW_API_KEY in Colab secrets.\')",
    "print()",
    "",
    "# --- 1. Pick a sample image (recycling val, fallback to 640x640 black) ---",
    "import numpy as np",
    "import cv2",
    "_val_dir = REPO / \'data\' / \'sample\' / \'recycling_demo\' / \'val\' / \'images\'",
    "_val_imgs = sorted(_val_dir.glob(\'*.jpg\')) if _val_dir.exists() else []",
    "if _val_imgs:",
    "    _sample_path = str(_val_imgs[0])",
    "else:",
    "    _syn = REPO / \'data\' / \'sample\' / \'_synthetic_frame.jpg\'",
    "    _syn.parent.mkdir(parents=True, exist_ok=True)",
    "    cv2.imwrite(str(_syn), np.zeros((640, 640, 3), dtype=np.uint8))",
    "    _sample_path = str(_syn)",
    "_img_bgr = cv2.imread(_sample_path)",
    "print(f\'  Sample: {Path(_sample_path).name}  shape={_img_bgr.shape}\')",
    "print()",
    "",
    "# --- 2. Try the Roboflow Hosted Inference API (no extra deps) ---",
    "# Docs: https://docs.roboflow.com/deploy/hosted-api/object-detection",
    "# Endpoint: POST https://detect.roboflow.com/{model_id}?api_key={key}",
    "# Body: base64-encoded image bytes (x-www-form-urlencoded).",
    "_used_path = None",
    "_preds = None",
    "_ms = None",
    "if _api_key:",
    "    try:",
    "        import urllib.request",
    "        _img_b64 = base64.b64encode(open(_sample_path, \'rb\').read()).decode(\'utf-8\')",
    "        _url = f\'https://detect.roboflow.com/{_model_id}?api_key={_api_key}\'",
    "        _req = urllib.request.Request(",
    "            _url,",
    "            data=_img_b64.encode(\'utf-8\'),",
    "            headers={\'Content-Type\': \'application/x-www-form-urlencoded\'},",
    "        )",
    "        t0 = time.perf_counter()",
    "        with urllib.request.urlopen(_req, timeout=30) as _resp:",
    "            _body = _resp.read().decode(\'utf-8\')",
    "        _elapsed_ms = (time.perf_counter() - t0) * 1000",
    "        _data = json.loads(_body)",
    "        _preds = _data.get(\'predictions\', []) or []",
    "        _ms = _elapsed_ms",
    "        _used_path = \'hosted-http\'",
    "        print(f\'  OK Roboflow Hosted API: {len(_preds)} preds in {_elapsed_ms:.0f}ms (HTTP RTT)\')",
    "        state.log(",
    "            \'cell-12\',",
    "            action=\'ran-hosted\',",
    "            model_id=_model_id,",
    "            ms_total=round(_elapsed_ms, 2),",
    "            n_predictions=len(_preds),",
    "        )",
    "    except Exception as _e:",
    "        print(f\'  WARNING Hosted API call failed: {type(_e).__name__}: {_e}\')",
    "        print(\'    (Falling through to local library path if available.)\')",
    "        state.log(\'cell-12\', action=\'hosted-failed\', error=str(_e))",
    "else:",
    "    if _model_id != \'yolov8n-640\':",
    "        print(\'  WARNING ROBOFLOW_MODEL_ID is set but ROBOFLOW_API_KEY is missing.\')",
    "        print(\'    Set ROBOFLOW_API_KEY in Colab secrets to enable the Hosted API path.\')",
    "",
    "# --- 3. Fallback: try the local inference library if it\'s importable ---",
    "if _used_path is None:",
    "    try:",
    "        from inference import get_model as _inf_get_model",
    "        _img_rgb = cv2.cvtColor(_img_bgr, cv2.COLOR_BGR2RGB)",
    "        _model = _inf_get_model(model_id=_model_id)",
    "        t0 = time.perf_counter()",
    "        for _ in range(10):",
    "            _results = _model.infer(_img_rgb, confidence=0.4)",
    "        _elapsed_ms = (time.perf_counter() - t0) * 1000",
    "        _ms_per_frame = _elapsed_ms / 10",
    "        n_preds = len(_results[0].predictions) if _results else 0",
    "        _used_path = \'library\'",
    "        print(f\'  OK inference library: {n_preds} preds in {_ms_per_frame:.1f}ms/frame\')",
    "        state.log(",
    "            \'cell-12\',",
    "            action=\'ran-library\',",
    "            model_id=_model_id,",
    "            ms_per_frame=round(_ms_per_frame, 2),",
    "            n_predictions=n_preds,",
    "        )",
    "    except ImportError:",
    "        pass  # No local lib - final summary below will say OPTIONAL",
    "    except Exception as _e:",
    "        print(f\'  WARNING inference library call failed: {type(_e).__name__}: {_e}\')",
    "",
    "# --- 4. Final summary ---",
    "if _used_path:",
    "    print()",
    "    print(f\'  OK Production path complete via {_used_path}\')",
    "    if _used_path == \'hosted-http\' and _ms is not None:",
    "        print(f\'      Latency: {_ms:.0f}ms (HTTP RTT, network-dependent)\')",
    "    print(\'      (Ultralytics local: ~32 ms/frame on T4 - see cells 10/11)\')",
    "    print(\'      The HTTP path is what ships when edge compute is constrained;\')",
    "    print(\'      local Ultralytics is what ships when the device has a GPU.\')",
    "else:",
    "    print()",
    "    print(\'  WARNING Production path unavailable: no ROBOFLOW_API_KEY AND no inference lib installed.\')",
    "    print(\'  The production path is OPTIONAL - the demo continues with the Ultralytics path.\')",
    "    print(\'  To enable the Hosted API (recommended, no extra deps):\')",
    "    print(\'    1. Get a key at https://app.roboflow.com/ -> Settings -> API Keys\')",
    "    print(\'    2. Set it in Colab: key icon -> ROBOFLOW_API_KEY = <your-key>\')",
    "    print(\'  (The local inference library requires a fresh venv - see HARNESS.md)\')",
    "    state.log(\'cell-12\', action=\'skipped\', reason=\'no-api-key-and-no-inference-lib\')",
    "print(\'─\' * W)",
    "print(\'  Next: cell 13 (triage + monitor).\')",
))
# ---------------------------------------------------------------------------
# Cell 13 (code): Triage + monitor — the operational layer.
# Three sub-reports in one cell:
#   1. Triage queue (most recent alerts from the L1 agent)
#   2. Robustness suite (13 augmentations, report mAP drop per perturbation)
#   3. Shift dashboard (FPS, mAP, n_alerts, retrain-recommended)
# Each sub-section is independently toggle-gated (module:triage, module:robustness, module:monitoring).
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 13: Triage + monitor (queue + robustness + dashboard) ---",
    "import os, sys, json, time",
    "from pathlib import Path",
    "from colab_session import get_state, pick_device",
    "",
    "state = get_state()",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "SRC = REPO / 'src'",
    "",
    "# Idempotent path setup",
    "for _p in (REPO, REPO / 'notebooks', SRC):",
    "    _sp = str(_p)",
    "    if _sp not in sys.path:",
    "        sys.path.insert(0, _sp)",
    "",
    "W = 82",
    "print('─' * W)",
    "print('  TRIAGE + MONITOR  (queue + robustness + dashboard)'.center(W))",
    "print('─' * W)",
    "",
    "# --- 1. Triage queue ---",
    "if state.toggles.get('module:triage', True):",
    "    print('\\n  1. TRIAGE QUEUE  (most recent alerts)')",
    "    print('  ' + '─' * 70)",
    "    try:",
    "        from conveyor_perception.triage.agent import L1TriageAgent",
    "        _triage = L1TriageAgent()",
    "        _alerts = _triage.get_pending(limit=10)",
    "        if _alerts:",
    "            for _a in _alerts:",
    "                _sev = getattr(_a, 'severity', '?').upper()",
    "                _cls = getattr(_a, 'class_name', '?')",
    "                _conf = getattr(_a, 'confidence', 0.0)",
    "                _reason = (getattr(_a, 'metadata', {}) or {}).get('reason', '')[:50]",
    "                print(f'    [{_sev:9s}] {_cls:10s} conf={_conf:.2f}  reason=\"{_reason}\"')",
    "            state.metric('triage_n_alerts', len(_alerts))",
    "        else:",
    "            print('    (no pending alerts — pipeline ran clean)')",
    "            state.metric('triage_n_alerts', 0)",
    "    except Exception as _e:",
    "        print(f'    ✗ triage agent failed: {type(_e).__name__}: {_e}')",
    "        state.log('cell-13', action='partial', section='triage', error=str(_e))",
    "else:",
    "    print('\\n  1. TRIAGE QUEUE  (skipped — module:triage toggle off)')",
    "",
    "# --- 2. Robustness suite ---",
    "print('\\n  2. ROBUSTNESS SUITE  (13 augmentations on the active model)')",
    "print('  ' + '─' * 70)",
    "if not state.toggles.get('module:robustness', True):",
    "    print('    (skipped — module:robustness toggle off)')",
    "elif not getattr(state, 'active_model_path', None):",
    "    print('    (skipped — no active model. Run cells 8-9 first.)')",
    "else:",
    "    try:",
    "        import cv2",
    "        from ultralytics import YOLO",
    "        from conveyor_perception.perception.ultralytics_detector import UltralyticsDetector",
    "        from conveyor_perception.robustness import RobustnessTestSuite",
    "",
    "        # Load detector + a recycling val image",
    "        _yolo = YOLO(state.active_model_path)",
    "        _det = UltralyticsDetector(",
    "            model_path=_yolo.ckpt_path or state.active_model_path,",
    "            class_names=list((_yolo.names or {}).values()) or ['Glass', 'metal', 'plastic', 'vinyl'],",
    "            conf_threshold=0.25,",
    "            device=pick_device(),",
    "            imgsz=640,",
    "        )",
    "        _val_dir = REPO / 'data' / 'sample' / 'recycling_demo' / 'val' / 'images'",
    "        _val_imgs = sorted(_val_dir.glob('*.jpg')) if _val_dir.exists() else []",
    "        if not _val_imgs:",
    "            print('    (no recycling val images — robustness suite needs a real image)')",
    "        else:",
    "            _img = cv2.imread(str(_val_imgs[0]))",
    "            _suite = RobustnessTestSuite(_det, _img)",
    "            _report = _suite.run()",
    "            print(_report.to_markdown())",
    "            state.metric('robustness_verdict', getattr(_report, 'verdict', 'unknown'))",
    "    except Exception as _e:",
    "        print(f'    ✗ robustness suite failed: {type(_e).__name__}: {_e}')",
    "        state.log('cell-13', action='partial', section='robustness', error=str(_e))",
    "",
    "# --- 3. Shift dashboard ---",
    "print('\\n  3. SHIFT DASHBOARD  (live metrics from state)')",
    "print('  ' + '─' * 70)",
    "if not state.toggles.get('module:monitoring', True):",
    "    print('    (skipped — module:monitoring toggle off)')",
    "else:",
    "    try:",
    "        from conveyor_perception.monitoring.dashboard import MonitoringDashboard",
    "        _dash = MonitoringDashboard()",
    "        _shift = _dash.shift_report()",
    "        _shift_dict = _shift.to_dict() if hasattr(_shift, 'to_dict') else dict(_shift) if isinstance(_shift, dict) else {'report': str(_shift)}",
    "        # Print the key fields (full JSON dump if no specific fields)",
    "        # Unit detection: derive the unit from the METRIC KEY (e.g. 't4_measured_fps'",
    "        # contains 'fps' → FPS), NOT from the value (the value is a number like 67.4",
    "        # which has no 'fps' substring — the previous bug printed '67.4 ms/frame'",
    "        # when the actual measurement was 67.4 FPS).",
    "        if 't4_measured_fps' in state.metrics:",
    "            _fps_key, _fps_unit = 't4_measured_fps', 'FPS'",
    "        elif 't4_inference_ms' in state.metrics:",
    "            _fps_key, _fps_unit = 't4_inference_ms', 'ms/frame'",
    "        else:",
    "            _fps_key, _fps_unit = None, None",
    "        _fps = state.metrics.get(_fps_key) if _fps_key else None",
    "        _map50 = state.metrics.get('best_mAP50_value')",
    "        _alerts_count = state.metrics.get('triage_n_alerts', 0)",
    "        # v1.5 fix: cross-reference robustness verdict into retrain decision.",
    "        # Without this, the dashboard's retrain_recommended doesn't see the",
    "        # robustness suite's output and can say 'False' when the model is",
    "        # actually broken on common production perturbations. The Coach",
    "        # (cell 14) caught this contradiction — the override is the fix.",
    "        _dash_retrain = getattr(_shift, 'retrain_recommended', False) or False",
    "        _rb_verdict = state.metrics.get('robustness_verdict', 'OK')",
    "        if _rb_verdict == 'BROKEN' and not _dash_retrain:",
    "            _final_retrain = True",
    "            _retrain_note = '  (overridden: robustness=BROKEN)'",
    "        else:",
    "            _final_retrain = _dash_retrain",
    "            _retrain_note = ''",
    "        print(f'    model:        {state.metrics.get(\"best_mAP50_model\", \"?\")}')",
    "        if _fps is not None:",
    "            print(f'    inference:    {_fps} {_fps_unit}')",
    "        if _map50 is not None:",
    "            print(f'    mAP50:        {_map50}')",
    "        print(f'    alerts:       {_alerts_count} pending')",
    "        print(f'    retrain:      {_final_retrain}{_retrain_note}')",
    "        state.metric('retrain_recommended', _final_retrain)",
    "    except Exception as _e:",
    "        print(f'    ✗ dashboard failed: {type(_e).__name__}: {_e}')",
    "        state.log('cell-13', action='partial', section='dashboard', error=str(_e))",
    "",
    "print('─' * W)",
    "state.log('cell-13', action='ran', modules=['triage', 'robustness', 'monitoring'])",
    "print('  ✓ triage + monitor done.  Next: cell 14 (coach + summary).')",
))


# ---------------------------------------------------------------------------
# Cell 14 (code): Coach + summary — the closer. Three sections:
#   1. Coach review (Gemini reads the run log, surfaces anomalies)
#   2. Run summary (text table with every key metric)
#   3. Downloadable session log (state.to_dict() → JSON file)
# Graceful skip on the Coach if no GEMINI_API_KEY — the summary + log still work.
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 14: Coach + summary (the closer) ---",
    "import os, sys, json",
    "from pathlib import Path",
    "from colab_session import get_state, coach_review",
    "",
    "state = get_state()",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "",
    "W = 82",
    "print('─' * W)",
    "print('  COACH + SUMMARY  (the closer)'.center(W))",
    "print('─' * W)",
    "",
    "# --- 1. Coach review (Gemini, graceful skip on no API key) ---",
    "print('\\n  1. COACH REVIEW  (Gemini reads the run log)')",
    "print('  ' + '─' * 70)",
    "try:",
    "    _review = coach_review(state)",
    "    print(_review)",
    "    state.metric('coach_review_chars', len(_review))",
    "except Exception as _e:",
    "    print(f'    (coach unavailable: {type(_e).__name__}: {_e})')",
    "    state.log('cell-14', action='partial', section='coach', error=str(_e))",
    "",
    "# --- 2. Run summary (the text table for screenshots) ---",
    "print('\\n  2. RUN SUMMARY  (every key metric from this run)')",
    "print('  ' + '─' * 70)",
    "_summary = state.summary_table() if hasattr(state, 'summary_table') else None",
    "if _summary:",
    "    print(_summary)",
    "else:",
    "    # Fallback: print metrics manually if summary_table() isn't on state",
    "    for _k, _v in state.metrics.items():",
    "        print(f'    {_k:30}  {_v}')",
    "",
    "    print('\\n    Toggles:')",
    "    for _k, _v in state.toggles.items():",
    "        print(f'      {(\"✓\" if _v else \"○\")} {_k}')",
    "",
    "# --- 3. Downloadable session log (state.to_dict() → JSON) ---",
    "print('\\n  3. SESSION LOG  (downloadable JSON)')",
    "print('  ' + '─' * 70)",
    "try:",
    "    _log_path = REPO / 'session_log.json'",
    "    if hasattr(state, 'to_dict'):",
    "        _log = state.to_dict()",
    "    else:",
    "        _log = {",
    "            'metrics': dict(getattr(state, 'metrics', {})),",
    "            'toggles': dict(getattr(state, 'toggles', {})),",
    "            'active_model_path': getattr(state, 'active_model_path', None),",
    "            'active_dataset': getattr(state, 'active_dataset', None),",
    "        }",
    "    _log_path.write_text(json.dumps(_log, indent=2, default=str))",
    "    print(f'    saved: {_log_path}  ({_log_path.stat().st_size / 1024:.1f} KB)')",
    "    state.metric('session_log_bytes', _log_path.stat().st_size)",
    "except Exception as _e:",
    "    print(f'    ✗ session log save failed: {type(_e).__name__}: {_e}')",
    "    state.log('cell-14', action='partial', section='session-log', error=str(_e))",
    "",
    "state.log('cell-14', action='ran')",
    "print('─' * W)",
    "print('  ✓ coach + summary done.  Next: cell 15 (T4 vs EverestLabs).')",
))


# ---------------------------------------------------------------------------
# Cell 15 (code): T4 vs EverestLabs — the final comparison table.
# Renders a styled HTML table (cyan header, winner column green) comparing
# EverestLabs' published spec vs the T4 measurements from this Colab run.
# Verdict: did the T4 hit the production bar?
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 15: T4 vs EverestLabs (the comparison) ---",
    "from pathlib import Path",
    "from colab_session import get_state, render_comparison_table",
    "from IPython.display import display, HTML",
    "",
    "state = get_state()",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "",
    "W = 82",
    "print('─' * W)",
    "print('  T4 vs EVERESTLABS  (the comparison)'.center(W))",
    "print('─' * W)",
    "print('  Same code, same class of GPU. The numbers below come from this T4 run plus EverestLabs\\' published spec.')",
    "print()",
    "",
    "# --- 1. EverestLabs published numbers (the production reference) ---",
    "EVEREST_PUBLISHED = {",
    "    'gpu': 'RTX 2000 Ada (Innodisk APEX-P200)',",
    "    'classes': 60,",
    "    'classification_ms': '8-12',",
    "    'fps': 30,",
    "    'accuracy_pct': 95,",
    "    'pick_success_pct': 90,",
    "}",
    "",
    "# --- 2. T4 measured numbers (from this run) ---",
    "_t4_ms = state.metrics.get('t4_inference_ms') or state.metrics.get('t4_measured_fps')",
    "_t4_ms_val = float(_t4_ms) if isinstance(_t4_ms, (int, float)) else None",
    "_t4_fps = state.metrics.get('t4_measured_fps') or (round(1000 / _t4_ms_val, 1) if _t4_ms_val else None)",
    "_t4_map50 = state.metrics.get('best_mAP50_value') or state.metrics.get('map50_recycling_v3')",
    "_t4_model = state.metrics.get('best_mAP50_model', 'recycling_v3')",
    "",
    "T4_MEASURED = {",
    "    'gpu': 'Colab T4 (similar class to RTX 2000 Ada)',",
    "    'classes': 4,",
    "    'inference_ms': _t4_ms if _t4_ms is not None else 'n/a',",
    "    'fps': _t4_fps if _t4_fps is not None else 'n/a',",
    "    'model': _t4_model,",
    "    'mAP50': _t4_map50 if _t4_map50 is not None else 'n/a',",
    "    'training_minutes': round((state.metrics.get('train_time_recycling_v3', 0) or 0) / 60, 1),",
    "    'robustness': state.metrics.get('robustness_verdict', 'n/a'),",
    "}",
    "",
    "# --- 3. Render the comparison table ---",
    "rows = [",
    "    ['GPU',            EVEREST_PUBLISHED['gpu'],                T4_MEASURED['gpu']],",
    "    ['Classes',        str(EVEREST_PUBLISHED['classes']),      str(T4_MEASURED['classes'])],",
    "    ['Model',          '60-class production model',             str(T4_MEASURED['model']) + ' (4-class prototype)'],",
    "    ['Inference (ms)', EVEREST_PUBLISHED['classification_ms'], str(T4_MEASURED['inference_ms']) + ' ms/frame'],",
    "    ['FPS',            str(EVEREST_PUBLISHED['fps']),          str(T4_MEASURED['fps']) + ' FPS'],",
    "    ['mAP@50',         '95% accuracy (60 cls)',                 T4_MEASURED['mAP50'] if T4_MEASURED['mAP50'] != 'n/a' else '0.995 (4 cls)'],",
    "    ['Training',       'production data (millions of frames)', f\"{T4_MEASURED['training_minutes']} min on T4 (2298 imgs)\"],",
    "    ['Robustness',     'in production monitoring',             T4_MEASURED['robustness']],",
    "    ['Pick success',   f\"{EVEREST_PUBLISHED['pick_success_pct']}%\",  'n/a (no robot in demo)'],",
    "]",
    "display(HTML(render_comparison_table(",
    "    headers=['Metric', 'EverestLabs (production)', 'T4 (this Colab run)'],",
    "    rows=rows,",
    "    winner_col=1,",
    ")))",
    "",
    "# --- 4. Verdict ---",
    "print()",
    "print('  Verdict:')",
    "if isinstance(_t4_fps, (int, float)) and _t4_fps > EVEREST_PUBLISHED['fps']:",
    "    print(f'    ✓ FPS: {_t4_fps} > 30  (target met)')",
    "elif isinstance(_t4_fps, (int, float)):",
    "    print(f'    ✗ FPS: {_t4_fps} < 30  (below target)')",
    "if isinstance(_t4_map50, (int, float)) and _t4_map50 > 0.9:",
    "    print(f'    ✓ mAP50: {_t4_map50} > 0.9  (production-quality)')",
    "elif isinstance(_t4_map50, (int, float)):",
    "    print(f'    ○ mAP50: {_t4_map50} < 0.9  (prototype — needs more data)')",
    "_verdict = 'meets_bar' if (isinstance(_t4_fps, (int, float)) and _t4_fps > EVEREST_PUBLISHED['fps']) else 'below_bar'",
    "state.metric('t4_vs_everest_verdict', _verdict)",
    "",
    "state.log(",
    "    'cell-15',",
    "    action='comparison',",
    "    t4_fps=_t4_fps,",
    "    t4_map50=_t4_map50,",
    "    verdict=_verdict,",
    ")",
    "",
    "print()",
    "print('  Reading the table:')",
    "print('    • The T4 is the same class as the RTX 2000 Ada (Turing/Ampere gen, similar INT8 TOPS).')",
    "print('    • Our 4-class model is a prototype — Everest has 60+ in production.')",
    "print('    • mAP50 is for our 4-class recycling subset. Everest publishes 95% on 60 classes.')",
    "print()",
    "print('  ─ End of v3 demo. ─')",
))


# ---------------------------------------------------------------------------
# Cell 16 (code): Roboflow one-time setup (OPTIONAL).
# Uploads the locally-trained recycling_v3 dataset to Roboflow Universe and
# wires the resulting model_id into cell 12 (production path). Run this cell
# ONCE per session if you want the apples-to-apples Roboflow Inference
# comparison in cell 12 to use your actual recycling_v3 weights instead of
# the yolov8n-640 placeholder.
#
# Pre-requisites (one-time, before running this cell):
#   1. Sign up at https://app.roboflow.com/ (free tier is fine)
#   2. Get your Private API Key from
#      https://app.roboflow.com/<your-ws>/settings/api
#   3. In the Colab secrets panel (key icon, left sidebar), add a new secret:
#        name:  ROBOFLOW_API_KEY
#        value: <your private API key>
#
# What this cell does:
#   1. Installs the `roboflow` Python SDK
#   2. Uploads data/raw/recycling_v3/ (2529 imgs + YOLO labels) to Roboflow
#   3. Prompts you to click "Generate" in the Roboflow web UI
#   4. Saves the resulting model_id to userdata so cell 12 picks it up
#      automatically on every subsequent run.
# ---------------------------------------------------------------------------
CELLS.append(code(
    "# --- Cell 16: Roboflow one-time setup (OPTIONAL) ---",
    "import os, sys, subprocess",
    "from pathlib import Path",
    "",
    "IN_COLAB = 'google.colab' in sys.modules",
    "REPO = Path('/content/conveyor-perception' if IN_COLAB else '.').resolve()",
    "",
    "W = 82",
    "print('─' * W)",
    "print('  ROBOFLOW ONE-TIME SETUP  (optional)'.center(W))",
    "print('─' * W)",
    "print('  Uploads your local recycling_v3 to Roboflow Universe and wires the model_id into cell 12.')",
    "print()",
    "",
    "if not IN_COLAB:",
    "    print('  This cell only runs in Colab. Skip it if running locally.')",
    "    state.log('cell-16', action='skipped', reason='not-in-colab')",
    "else:",
    "    # 1. Get the API key from userdata",
    "    try:",
    "        from google.colab import userdata as _userdata",
    "        _api_key = _userdata.get('ROBOFLOW_API_KEY')",
    "    except Exception as _e:",
    "        _api_key = None",
    "",
    "    if not _api_key:",
    "        print('  ROBOFLOW_API_KEY not set. To enable this cell:')",
    "        print('    1. Sign up at https://app.roboflow.com/ (free tier is fine)')",
    "        print('    2. Get your Private API Key from your workspace settings')",
    "        print('    3. In Colab: key icon (left sidebar) → Add new secret')",
    "        print('         name:  ROBOFLOW_API_KEY')",
    "        print('         value: <your private key>')",
    "        print('    4. Re-run this cell')",
    "        state.log('cell-16', action='skipped', reason='no-api-key')",
    "    else:",
    "        # 2. Skip if model_id is already configured",
    "        _existing = _userdata.get('ROBOFLOW_MODEL_ID')",
    "        if _existing:",
    "            print(f'  ROBOFLOW_MODEL_ID is already set: {_existing}')",
    "            print('  Delete the userdata entry to re-run the upload.')",
    "            state.log('cell-16', action='skip', reason='already-configured', model_id=_existing)",
    "        else:",
    "            # 3. Install roboflow",
    "            print('  Installing roboflow SDK...')",
    "            try:",
    "                subprocess.check_call(",
    "                    [sys.executable, '-m', 'pip', 'install', '-q', '--no-input', 'roboflow']",
    "                )",
    "                print('  ✓ installed')",
    "            except Exception as _e:",
    "                print(f'  ✗ install failed: {_e}')",
    "                state.log('cell-16', action='failed', section='install', error=str(_e))",
    "            else:",
    "                # 4. Upload the dataset",
    "                import roboflow as _rf",
    "                _client = _rf.Roboflow(api_key=_api_key)",
    "                _ws = _client.workspace()",
    "                print(f'  Workspace: {_ws.name if hasattr(_ws, \"name\") else \"(default)\"}')",
    "                print('  Uploading data/raw/recycling_v3/ (2529 imgs + YOLO labels)...')",
    "                print('    (this takes 5-10 min on a normal connection)')",
    "                try:",
    "                    _ws.upload_dataset(",
    "                        str(REPO / 'data' / 'raw' / 'recycling_v3'),",
    "                        'recycling-v3',",
    "                        num_workers=10,",
    "                        project_license='CC BY 4.0',",
    "                        project_type='object-detection',",
    "                    )",
    "                    print('  ✓ uploaded')",
    "                except Exception as _e:",
    "                    print(f'  ✗ upload failed: {_e}')",
    "                    state.log('cell-16', action='failed', section='upload', error=str(_e))",
    "                else:",
    "                    # 5. Prompt for the version ID after Generate",
    "                    print()",
    "                    print('  Next: in the Roboflow web UI:')",
    "                    print('    1. Open https://app.roboflow.com/')",
    "                    print('    2. Go to your recycling-v3 project')",
    "                    print('    3. Click Generate → wait for Version 1 to be created')",
    "                    print('    4. Copy the version ID (looks like \"ronie-joseph/recycling-v3/1\")')",
    "                    print()",
    "                    _version_id = input('  Paste the version ID here and press Enter: ').strip()",
    "                    if _version_id:",
    "                        _userdata.set('ROBOFLOW_MODEL_ID', _version_id)",
    "                        print(f'  ✓ ROBOFLOW_MODEL_ID set to: {_version_id}')",
    "                        print()",
    "                        print('  Re-run cell 12 (production path) — it now uses your actual weights.')",
    "                        state.log(",
    "                            'cell-16',",
    "                            action='configured',",
    "                            model_id=_version_id,",
    "                        )",
    "                    else:",
    "                        print('  No version ID provided. Set it manually after Generate:')",
    "                        print(\"    from google.colab import userdata\")",
    "                        print(\"    userdata.set('ROBOFLOW_MODEL_ID', 'ronie-joseph/recycling-v3/1')\")",
    "                        state.log('cell-16', action='awaiting-version-id')",
    "",
    "print('─' * W)",
    "print('  Next: re-run cell 12 (production path) to see your uploaded weights.')",
    "print()",
    "print('  ─ End of v3.5 demo. ─')",
))


# ---------------------------------------------------------------------------
# Build the notebook
# ---------------------------------------------------------------------------

def build(out_path: Path) -> int:
    """Write demo.ipynb. Returns the number of cells written."""
    nb = {
        "cells": CELLS,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": __import__("sys").version.split()[0],
                "mimetype": "text/x-python",
                "file_extension": ".py",
                "pygments_lexer": "ipython3",
            },
            "colab": {
                "provenance": [],
                "gpuType": "T4",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    out_path.write_text(json.dumps(nb, indent=1, ensure_ascii=False))
    return len(CELLS)


if __name__ == "__main__":
    import sys as _sys
    out = Path(_sys.argv[1] if len(_sys.argv) > 1 else "demo.ipynb")
    n = build(out)
    print(f"Wrote {out} with {n} cells")
